In [6]:
import numpy as np 

In [7]:
arr1=np.array([1,2,3,4,5,6,7,8,9]) #creating 1 dimensional array
print(arr1)
print(arr1.ndim) #prints dimension of array. Here array is 1 dimensional
print(arr1.dtype) #prints datatype of array
print(arr1.size) #prints no. of elements in array

[1 2 3 4 5 6 7 8 9]
1
int64
9


In [8]:
arr2=np.array([[1.,2.,3.],[5.,6.,7.]]) # creating array 2 dimensional array
print(arr2)
print(arr2.ndim) # Here array is 2 dimensional
print(arr2.dtype) 
print(arr2.size)
print(arr2.shape) #prints (no. of rows,no. of columns) in an array

[[1. 2. 3.]
 [5. 6. 7.]]
2
float64
6
(2, 3)


In [9]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,22,55]]]) #creating 3 dimensional array
print(arr3)
print(arr3.ndim) # Here array is 3 dimensional
print(arr3.dtype)
print(arr3.size)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 22 55]]]
3
int64
12
(2, 2, 3)


In [10]:
arr4=np.array([12,24,36,48,60,72,84,96,108,120,132,144]) # creating array
print(arr4)
print(arr4[1]) #prints element of an array at index positiion 1 i.e from starting. Indexing starts from 0
print(arr4[-2]) #prints element of an array at index positiion -2 i.e from backwards. Indexing starts from -1

[ 12  24  36  48  60  72  84  96 108 120 132 144]
24
132


In [11]:
store=np.arange(2,11) #arranges the array from 2 to n-1 i.e 10
print(store)

[ 2  3  4  5  6  7  8  9 10]


In [12]:
temp=arr4.reshape(4,3) # reshaping the array4 in 4 rows and 3 columns with its existing elements
print(temp)

[[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]
 [120 132 144]]


In [13]:
x=np.array([10,20,30])
y=np.array([30,20,10])
print("Addition : ",x+y) # Add two arrays
print("Subtraction : ",x-y) # Subtract two arrays
print("Multiplication : ",x*y) # Multiply two arrays
print("Division : ",x/y) # Divide two arrays
print("Power : ",x**y) # Power of x raised to y

Addition :  [40 40 40]
Subtraction :  [-20   0  20]
Multiplication :  [300 400 300]
Division :  [0.33333333 1.         3.        ]
Power :  [ 5076944270305263616 -2101438300051996672      590490000000000]


In [14]:
print(arr1)
print(arr1.max()) # prints max element in an array
print(arr1.min()) # prints min element in an array
print(np.argmax(arr1)) # prints index of max element in an array
print(np.argmin(arr1)) # prints index of min element in an array

[1 2 3 4 5 6 7 8 9]
9
1
8
0


In [15]:
?arr4

Type:        ndarray
String form: [ 12  24  36  48  60  72  84  96 108 120 132 144]
Length:      12
File:        c:\users\shrad\appdata\roaming\python\python312\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of cr

In [ ]:
print(arr1)
print(np.diff(arr1)) # prints the diffference between two consecutive elements in an array. Here difference is 1 because each element in the array appears serially

[1 2 3 4 5 6 7 8 9]
[1 1 1 1 1 1 1 1]


In [ ]:
np.linspace(8,45,num=8) # prints the values assigned to num in the specified range. Here specified range is 8 to 45

array([ 8.        , 13.28571429, 18.57142857, 23.85714286, 29.14285714,
       34.42857143, 39.71428571, 45.        ])