In [ ]:
import numpy as np #Import numpy library
print(np.__version__) #Check Version

2.3.1


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5],[3,6,5],[2,7,5]])
print(arr)
print(arr.shape)
print(arr.dtype)

[[1 2 3]
 [3 4 5]
 [3 6 5]
 [2 7 5]]
(4, 3)
int64
[[1 3 3 2]
 [2 4 6 7]
 [3 5 5 5]]
7
[[1 2 3 3]
 [4 5 3 6]
 [5 2 7 5]]
[[1 2 3]
 [2 4 5]
 [3 6 5]
 [3 7 5]]
[[1 2 3]
 [3 4 5]
 [3 5 6]
 [2 5 7]]


In [13]:
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))

[[1 2 3]
 [2 4 5]
 [3 6 5]
 [3 7 5]]
[[1 2 3]
 [3 4 5]
 [3 5 6]
 [2 5 7]]


In [12]:
print(arr.reshape(3,4))


[[1 2 3 3]
 [4 5 3 6]
 [5 2 7 5]]


In [11]:
print(arr.max())


7


In [10]:
print(arr.swapaxes(0,1))


[[1 3 3 2]
 [2 4 6 7]
 [3 5 5 5]]


In [14]:
arr1=np.zeros((3,4),dtype="int")
print(arr1)
print(arr1.shape)
print(arr1.dtype)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
int64


In [8]:
import numpy as np
zero_arr=np.zeros(5)
print(zero_arr)
zero_arr.dtype
zero_arr.astype(np.int32)

[0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 0], dtype=int32)

In [9]:
np.linspace(arr,1,10)

array([[[1.        , 2.        , 3.        ],
        [3.        , 4.        , 5.        ],
        [3.        , 6.        , 5.        ],
        [2.        , 7.        , 5.        ]],

       [[1.        , 1.88888889, 2.77777778],
        [2.77777778, 3.66666667, 4.55555556],
        [2.77777778, 5.44444444, 4.55555556],
        [1.88888889, 6.33333333, 4.55555556]],

       [[1.        , 1.77777778, 2.55555556],
        [2.55555556, 3.33333333, 4.11111111],
        [2.55555556, 4.88888889, 4.11111111],
        [1.77777778, 5.66666667, 4.11111111]],

       [[1.        , 1.66666667, 2.33333333],
        [2.33333333, 3.        , 3.66666667],
        [2.33333333, 4.33333333, 3.66666667],
        [1.66666667, 5.        , 3.66666667]],

       [[1.        , 1.55555556, 2.11111111],
        [2.11111111, 2.66666667, 3.22222222],
        [2.11111111, 3.77777778, 3.22222222],
        [1.55555556, 4.33333333, 3.22222222]],

       [[1.        , 1.44444444, 1.88888889],
        [1.88888889, 2.3

In [20]:
arr=np.zeros((3,4))
print(arr)
arr1=np.zeros((3,4),dtype="int")
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
arr=np.ones((3,4))
print(arr)
arr1=np.ones((3,4),dtype="int")
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
